# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(758, 513)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comments_label = QtWidgets.QLabel(self.centralwidget)
        self.comments_label.setGeometry(QtCore.QRect(530, 10, 81, 21))
        self.comments_label.setObjectName("comments_label")
        self.entercomments_label = QtWidgets.QLabel(self.centralwidget)
        self.entercomments_label.setGeometry(QtCore.QRect(620, 30, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.entercomments_label.setFont(font)
        self.entercomments_label.setObjectName("entercomments_label")
        self.commentbox = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.commentbox.setGeometry(QtCore.QRect(530, 50, 231, 371))
        self.commentbox.setObjectName("commentbox")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(80, 440, 271, 41))
        self.textEdit.setObjectName("textEdit")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(360, 440, 75, 23))
        self.send.setObjectName("send")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(510, 460, 75, 23))
        self.next.setObjectName("next")
        self.next.clicked.connect(self.change_image)
        self.like = QtWidgets.QPushButton(self.centralwidget)
        self.like.setGeometry(QtCore.QRect(0, 460, 61, 23))
        self.like.setObjectName("like")
        self.likes = QtWidgets.QLabel(self.centralwidget)
        self.likes.setGeometry(QtCore.QRect(10, 430, 51, 21))
        self.likes.setObjectName("likes")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(10, 10, 511, 411))
        self.photo.setAutoFillBackground(False)
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("C:/Users/HP/Pictures/meme.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionrecent = QtWidgets.QAction(MainWindow)
        self.actionrecent.setObjectName("actionrecent")
        self.actionlogs = QtWidgets.QAction(MainWindow)
        self.actionlogs.setObjectName("actionlogs")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comments_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Comments</span></p></body></html>"))
        self.entercomments_label.setText(_translate("MainWindow", "Enter your comments"))
        self.send.setText(_translate("MainWindow", "Send"))
        self.next.setText(_translate("MainWindow", "Next"))
        self.like.setText(_translate("MainWindow", "Like"))
        self.likes.setText(_translate("MainWindow", "Likes"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionrecent.setText(_translate("MainWindow", "recent"))
        self.actionlogs.setText(_translate("MainWindow", "logs"))

    def change_image(self):
        self.photo.setPixmap(QtGui.QPixmap("cat.png"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
